### ISSUE TITLE
Support for postServeAction

### ISSUE THREAD

**Issue by abbasadel** [spring-cloud/spring-cloud-contract#1078]
Hi,

I'm trying to use this [wiremock extension](https://github.com/wiremock/wiremock-webhooks-extension) which uses `postServeAction` in wiremock DSL. 

Is there any way to use `postServeAction` with the currect version with SCC or maybe support it in the future?

Thanks,
Abbas

**Comment by marcingrzejszczak** [comment]
Hello @abbasadel ! Thanks for filing the issue. Can you explain why would you need this feature when doing contract tests? I understand that you want to use the asynchronous response from WireMock, but why would it be needed for contract tests as such?

**Comment by abbasadel** [comment]
Hi @marcingrzejszczak,

I want to be able to simulate calling an endpoint with certain parameters and then I receive a web hook call once the request is processed with the same parameters. 

This is how some of my applications interact with an external API. 

It was possible to have that functionality using purely wiremock json but It was not possible to reuse that json with contract definitions. 

It would be great if SCC provides it.

**Comment by marcingrzejszczak** [comment]
Since extending the DSL would require broader discussions, and I don't want you to be blocked in any way, I think we can have a workaround for your issue...

First, you can register your custom transformers via the `org.springframework.cloud.contract.verifier.dsl.wiremock.WireMockExtensions` interface. You can read more about this here https://cloud.spring.io/spring-cloud-static/Greenwich.SR2/single/spring-cloud.html#_registering_your_own_wiremock_extension . By using this extension, you can write your own, that will delegate to the `postServeAction` when the proper request was found (i.e. when the the request / response is related to the contract that you would like to use the `postServeAction`).

Another option is to use the `org.springframework.cloud.contract.stubrunner.HttpServerStubConfigurer` class that allows you to hook in customization for your `HttpServerStub`s. In your case that is the `WireMockHttpServerStub`. There is also a typed configurer - `org.springframework.cloud.contract.stubrunner.provider.wiremock.WireMockHttpServerStubConfigurer`. You can read more about this here https://cloud.spring.io/spring-cloud-static/Greenwich.SR2/single/spring-cloud.html#_configuring_http_server_stubs . E.g. in case for `fraud-detection` you would like to use that special extension you can call 

```groovy
@CompileStatic
	static class HttpsForFraudDetection extends WireMockHttpServerStubConfigurer {

		private static final Log log = LogFactory.getLog(HttpsForFraudDetection)

		@Override
		WireMockConfiguration configure(WireMockConfiguration httpStubConfiguration, HttpServerStubConfiguration httpServerStubConfiguration) {
			if (httpServerStubConfiguration.stubConfiguration.artifactId == "fraudDetectionServer") {
				return httpStubConfiguration
						.extensions("my-extension")
			}
			return httpStubConfiguration
		}
	}
```

Hopefully this workarounds will help you to proceed. I won't close this issue since it can start a discussion about how to extend the contract to allow such extensions to hook in explicitly.
