### ISSUE TITLE
Message contract - embedded kafka - multiple topics

### ISSUE THREAD

**Issue by DawidSwinoga** [spring-cloud/spring-cloud-contract#1308]
I have a problem when I use kafka contracts with multpile topics definded in the EmbeddedKafka annotation. At first I thought it was a problem with the embedded kafka broker and I created this issue https://github.com/spring-projects/spring-kafka/issues/1352 . I received a reply that kafka consumers in the ContractVerifierKafkaStubMessagesInitializer.initialize are incorrectly initialized.

**Comment by kuzdi** [comment]
I encountered the same problem and managed to solve it - https://github.com/kuzdi/spring-cloud-contract-samples. However this is more of a workaround as it boils down to replacing groupId with random value rather than relying on kafkaProperties. https://github.com/spring-cloud/spring-cloud-contract/blob/704be942cffe2d01a85e0a8c282de31a1b88b8ad/spring-cloud-contract-verifier/src/main/java/org/springframework/cloud/contract/verifier/messaging/kafka/ContractVerifierKafkaStubMessagesInitializer.java#L48-L51

**Comment by marcingrzejszczak** [comment]
Would the option to use the actual Kafka broker via test containers like here [producer](https://github.com/spring-cloud-samples/spring-cloud-contract-samples/tree/3.0.x/producer_kafka_middleware) and here [consumer](https://github.com/spring-cloud-samples/spring-cloud-contract-samples/tree/3.0.x/consumer_kafka_middleware) be ok to you? Would it solve your problem?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.
