### ISSUE TITLE
Stubrunner pulls in Eureka and Config clients of client under test causing test to fail

### ISSUE THREAD

**Issue by mattreyuk** [spring-cloud/spring-cloud-contract#141]
I have a client I'm testing with Eureka and Spring Cloud Config clients included. When I run a client side test with my stub jar, the created stubrunner follows the default behavior of my client and attempts to connect to Eureka and Config Server. As `fail-fast` is also set, when it can't connect to Eureka or the default `localhost:8888` config server, it terminates and fails the test. 

My client under test runs with a `standalone` profile that turns off Eureka and Config clients.

It appears that the stubrunner container starts with a profile of `development` as when I setup configuration in `bootstrap.yml` for `development` to match my `standalone` profile, the stubrunner starts without issue, serves the stub data and the test completes successfully.

This `development` profile workaround is likely to cause problems for anyone who already has a profile of that name.

I have a project to demo this at https://github.com/mattreyuk/clientTest

**Comment by marcingrzejszczak** [comment]
Hi @mattreyuk . Sorry for the delay...

> It appears that the stubrunner container starts with a profile of development as when I setup configuration in bootstrap.yml for development to match my standalone profile, the stubrunner starts without issue, serves the stub data and the test completes successfully.

Stub runner doesn't start with such a profile. In fact Stub Runner starts with no profile. Can you elaborate more on this issue cause I don't really get it :/

**Comment by mattreyuk** [comment]
Hi Marcin - on vacation at the moment so a bit slow to respond. Did you try building the client test project I linked to? That illustrates the problem. Client service has Eureka and Config clients built in, test is run with profile that turns them off. When stubrunner starts up, it tries to contact Eureka, fails and falls back to trying to get to a config server on localhost and then dies because fail fast is set. Looking at logging from that failure, I saw it mention development so I setup a profile for that with eureka and config turned off and stub runner started without issue and the test passed.  I don't know why stubrunner is behaving like that but that's what I'm seeing.

**Comment by marcingrzejszczak** [comment]
Ok now I understood what you meant... I don't think it's related to stub runner and it's exactly the same problem as presented here https://github.com/spring-cloud/spring-cloud-contract/issues/174 (cc @kabennett ). 

In the `bootstrap.yml` you're setting values to connect to Service Discovery and then you'd like to clear them out in the test setup. That seems to be not possible at this moment. After the new year for sure we'll check this out. Currently you can either do as you have done until now - so define a profile in `bootstrap.yml` and reference it from your tests. Or you can pass a system prop to set it.

Another poor man's version is to define a static block with test properties in your test :|

```
static {
		System.setProperty("eureka.client.enabled", "false");
		System.setProperty("spring.cloud.config.enabled", "false");
		System.setProperty("spring.cloud.config.discovery.enabled", "false");
	}
```

I'll close this one since I've filed another one - https://github.com/spring-cloud/spring-cloud-commons/issues/156

cc @dsyer @spencergibb @ryanjbaxter
