### ISSUE TITLE
execute() in body() is not resolved with Kotlin DSL

### ISSUE THREAD

**Issue by huberchrigu** [spring-cloud/spring-cloud-contract#1447]
I have a Kotlin Contract

```package contracts

import org.springframework.cloud.contract.spec.ContractDsl.Companion.contract

contract {
    name = "Test"
    request {
        url = url("/test")
        method = POST
        body = body(
                mapOf(
                        "ConstructionYear" to value(producer(execute("getYear(2)")), consumer("2018"))
                )
        )
    }
    response {
        status = CREATED
        body = body(mapOf(
               "ConstructionYear" to fromRequest().body("$.ConstructionYear")
        ))
    }
}
```

which is turned into the test

```
@Test
	public void validate_aqua_premium() throws Exception {
		// given:
			WebTestClientRequestSpecification request = given()
					.body("{\"ConstructionYear\":{\"executionCommand\":\"getYear(2)\"}}");

		// when:
			WebTestClientResponse response = given().spec(request)
					.post("/test");

		// then:
			assertThat(response.statusCode()).isEqualTo(201);

		// and:
			DocumentContext parsedJson = JsonPath.parse(response.getBody().asString());
			assertThatJson(parsedJson).field("['ConstructionYear']").isEqualTo({
  "executionCommand" : "getYear(2)"
});
}
```

I'd expect the test's request body to be `{"ConstructionYear": "2018"}` (2018 is what the function `getYear(2)` returns). Then the response assertion should end like `...isEqualTo("2018")`. I use Spring Cloud version Hoxton.SR6.

**Comment by TYsewyn** [comment]
I just added a test based on your input and it looks like the issue is not related to the Kotlin support.
See https://github.com/spring-cloud/spring-cloud-contract/commit/ac639facdc3b24096362c26f36a438a7fc25df37.

Based on that test I'm expecting that something is going wrong during the test generation.
@marcingrzejszczak @OlgaMaciaszek Would you be able to take a look at this part of the project?

**Comment by marcingrzejszczak** [comment]
Hey @TYsewyn I'm pretty sure this one is connected to https://github.com/spring-cloud/spring-cloud-contract/issues/1485

**Comment by marcingrzejszczak** [comment]
I've managed to replicate this without Kotlin

**Comment by marcingrzejszczak** [comment]
Ok now I know what the problem is... We don't allow `execute(...)` to be executed for a particular part of the body. You need to call it for the whole body. Here we describe this in more depth - https://docs.spring.io/spring-cloud-contract/docs/current/reference/htmlsingle/#contract-dsl-custom-methods

**Comment by huberchrigu** [comment]
Thanks @marcingrzejszczak. It works after moving the whole response body to the execute() function.
