### ISSUE TITLE
Wiremock stubs not loaded correctly with resetToDefaultMappings() when using a custom stubs location

### ISSUE THREAD

**Issue by m-kay** [spring-cloud/spring-cloud-contract#1451]
When a custom stub location is configured in @AutoConfigureWireMock and during tests the resetToDefaultMappings() is called then the custom stubs location is not taken into account but the default location "mappings" is used.

You can check that in the sample here https://github.com/m-kay/wiremock-reset-test with the test `WiremockResetTestApplicationTests`. If stubs on [line 18](https://github.com/m-kay/wiremock-reset-test/blob/master/src/test/kotlin/com/github/mkay/wiremockresettest/WiremockResetTestApplicationTests.kt#L18) where configured to be in `classpath:/wiremock/mappings` it would work correctly because `mappings` is the default location.

**Comment by bono007** [comment]
### Summary
So the `com.github.tomakehurst.wiremock.WireMockServer` composes its stub mappings from 2 areas:

1. **The default Wiremock mappings: `wiremock/mappings`**
By default, it delegates to `com.github.tomakehurst.wiremock.core.WireMockApp` which maintains a `defaultMappingsLoader` obtained from `com.github.tomakehurst.wiremock.core.Options#mappingsLoader`. This turns out to be a `JsonFileMappingsSource(this.filesRoot.child("mappings"));` when no loader is explicitly set on the options object.

2. **The Spring Cloud Contract `stubs` mappings**
The `org.springframework.cloud.contract.wiremock.WireMockConfiguration` calls  `com.github.tomakehurst.wiremock.WireMockServer#addStubMapping` for the entries in the `stubs` property during its `registerStubs` method. The WireMockServer however, does not keep this state, nor does it consider this any of its "default mappings".

### Cause
This is an interesting one in that the `stubs` property is only known to SCC and set on the the WireMockServer during registerStubs method. The method that is being called in this test is directly on the WiremockServer and it does just what it was asked to do, it resets itself to its default mappings (`#1` above). It knows nothing about `#2`) as that is a SCC construct (the `stubs` property). 

### Options
A couple of options come to mind:

1. Mutate the `com.github.tomakehurst.wiremock.core.Options` so that when the stubs property is set, the mappingsloader becomes one that is capable of loading from the stubs location as well. 
(+) Would be able to control the reset from the native WiremockServer call
(+) The stubs are truly treated as part of the "default" mappings
(-) Added complexity of having to be able to load from multiple locations in the default (the default `filesRoot/mappings` and the `stubs` locations)
(-) Higher risk in treating stubs as default, may cause regression or at least ripple though and cause test refactors

2. Provide a helper method in `org.springframework.cloud.contract.wiremock.WireMockConfiguration` for `resetAllMappings` which would reset both the WireMockServer and then call registerStubs.
(+) Simple 
(+) Low risk, additive only
(-) It may be confusing when to use this new method vs. the one on WireMockServer, will need to educate. (Docs may be enough though).

@marcingrzejszczak what are your thoughts on the proposed options? Do any other come to mind?

**Comment by bono007** [comment]
Its also worth pointing out that the `org.springframework.cloud.contract.wiremock.WireMockTestExecutionListener` will reset the mappings (including adding the ones from the `stubs` location) after every test class and optionally after every test method (guarded by `wiremock.reset-mappings-after-each-test`).

**Comment by marcingrzejszczak** [comment]
> Do nothing. Document that the stubs are not considered part of the "default mappings" and instead leverage the wiremock.reset-mappings-after-each-test to cause the mappings (including the stubs) to be reset between test methods.

IMO this is the best approach. Let's improve the documentation. We can't support every use case. WDYT @bono007 ?

**Comment by bono007** [comment]
> IMO this is the best approach. Let's improve the documentation. We can't support every use case. WDYT @bono007 ?

@marcingrzejszczak I was leaning towards that as well. It feels like this could be solved by restructuring the test in question. @m-kay would using the above property allow you to restructure your test(s) in a way that could solve the issue?

**Comment by m-kay** [comment]
Well to fix the issue I just used the default location and moved my stubs. Just opened this issue because I found it confusing and had to debug why my tests didn't work. Maybe a hint to this behavior in the `@AutoConfigureWireMock#stubs` documentation would be helpful too.

**Comment by bono007** [comment]
@m-kay I agree that would be a great place to put a hint. I will update the docs accordingly.
