### ISSUE TITLE
Add YAML example to documentation section "2.4.2. Regular Expressions" 

### ISSUE THREAD

**Issue by AlbertoRota** [spring-cloud/spring-cloud-contract#1529]
**Is your feature request related to a problem? Please describe.**

The section "2.4.2. Regular Expressions" of the documentation is missing the YAML example of how to define a stub that will match several URLs.

**Describe the solution you'd like**

A YAML example of how to define a stub that will match against several URLs is added to the section "2.4.2. Regular Expressions" of the documentation.

**Describe alternatives you've considered**

**Additional context**

**Comment by AlbertoRota** [comment]
The example should look something like this:
`request:
  method: GET
  url: /12
  matchers:
    url:
      - regex: /[0-9]{2}
response:
  status: 200
  headers:
    Content-Type: text/plain
  body: 
    ...`

**Comment by marcingrzejszczak** [comment]
All the docs for contract parts are here https://github.com/spring-cloud/spring-cloud-contract/blob/2.2.x/docs/src/main/asciidoc/_project-features-contract.adoc (branch 2.2.x). The best way to tackle this would be to write the yaml in code and reference it in the docs, so that when you change the yaml the docs will automatically get updated. You can then run `./mvnw clean install -Pdocs -pl docs` and under `docs/target/` you'll be able to find the generated documentation.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
