### ISSUE TITLE
Dependency convergence error for org.ow2.asm:asm:5.0.4

### ISSUE THREAD

**Issue by tillias** [spring-cloud/spring-cloud-contract#1561]
Hello folks,

This is follow up from https://github.com/spring-projects/spring-boot/issues/24218

We're facing dependency convergence error when using spring-boot-starter-test and spring-cloud-starter-contract-verifier.

I have checked json-path:2.4.0 and it was released ages ago, so no coincidence old asm:5.0.4 is used.

Can you please advise what is the best way dealing with it?

Thanks

```
Dependency convergence error for org.ow2.asm:asm:5.0.4 paths to dependency are:
  +-org.springframework.boot:spring-boot-starter-test:2.3.1.RELEASE
    +-com.jayway.jsonpath:json-path:2.4.0
      +-net.minidev:json-smart:2.3
        +-net.minidev:accessors-smart:1.2
          +-org.ow2.asm:asm:5.0.4
and
  +-org.springframework.cloud:spring-cloud-starter-contract-verifier:2.2.3.RELEASE
    +-cglib:cglib:3.2.9
      +-org.ow2.asm:asm:7.0
```

@wilkinsona  mentioned that 

`Generally speaking Spring projects should use the CGLib that's bundled in spring-core rather than pulling it in as a dependency for exactly this sort of reason. Can you please raise this with the Spring Cloud Contract team so that they can explore making that switch?`

**Comment by bono007** [comment]
For a temporary workaround you can exclude the transitive dependency so that the latest version gets used. That is however, currently untested with `json-path -> json-smart -> accessors-smart`. I tested locally on a small project and it worked but that is not a thorough test. I will look at updating the version and getting it tested properly. 

In the meantime the exclusion looks like: 
```
<dependency>
  <groupId>org.springframework.cloud</groupId>
  <artifactId>spring-cloud-starter-contract-verifier</artifactId>
  <scope>test</scope>
  <exclusions>
    <exclusion>
      <groupId>org.ow2.asm</groupId>
      <artifactId>asm</artifactId>
    </exclusion>
  </exclusions>
</dependency>
```

**Comment by bono007** [comment]
For a temporary workaround you can exclude the transitive dependency so that the latest version gets used. That is however, currently untested with `json-path -> json-smart -> accessors-smart`. I tested locally on a small project and it worked but that is not a thorough test. I will look at updating the version and getting it tested properly. 

In the meantime the exclusion looks like: 
```
<dependency>
  <groupId>org.springframework.cloud</groupId>
  <artifactId>spring-cloud-starter-contract-verifier</artifactId>
  <scope>test</scope>
  <exclusions>
    <exclusion>
      <groupId>org.ow2.asm</groupId>
      <artifactId>asm</artifactId>
    </exclusion>
  </exclusions>
</dependency>
```

**Comment by bono007** [comment]
I started looking into how to bump the version of `asm` in the dependent libs used, ultimately the [accessors-smart](https://mvnrepository.com/artifact/net.minidev/accessors-smart/1.2) lib. It quickly unfolded into an archeological dig in trying to understand the triplicate of libs (`json-path -> json-smart -> accessors-smart`).

Its hard to tell if they are active or not. [Jayway json-path](https://mvnrepository.com/artifact/com.jayway.jsonpath/json-path) has not been updated since 2017. There are however, recent commits in the repo. I asked [this](https://github.com/json-path/JsonPath/issues/647#issuecomment-731608288).

As for [json-smart/accessors-smart](https://mvnrepository.com/artifact/net.minidev/json-smart) I see current activity for it only in the [Redhat](https://mvnrepository.com/artifact/net.minidev/json-smart?repo=redhat-ga) repo (with recent release in July 2020).

Does RestAssured JsonPath implementation cover the same functionality as Jayway JsonPath or it just RestAssured capabilities for JsonPath related tests?

Being bound to inactive repos is usually not a good thing. Pondering the thought of a replacement for json-path. I am sure that would be a huge change w/ a large blast radius. Just bringing it up though.

@marcingrzejszczak thoughts?

**Comment by bono007** [comment]
So the issue is both in `Spring Cloud Contract` and [Spring Boot Starter Test](https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-test/2.3.1.RELEASE) as they both pull in [JsonPath](https://mvnrepository.com/artifact/com.jayway.jsonpath/json-path/2.4.0) which in turn eventually pulls in the old asm. I found this out by adding exclusions on `asm` in Spring Cloud Contract only to find them still showing in my test application (via Spring Boot Starter Test). @wilkinsona am I missing something here?
 
The internal implementation details of smart-asserter should not be forced on its consumers. So my 1st thought was to fix it there. However, that library triplicate (`json-path -> json-smart` -> `smart-asserter`) all seem to be inactive. Based on that it seems that the best we can do is to exclude it transitively from JsonPath in both Spring Cloud Contract and Spring Boot Starter Test. Then it would pick up the latest version at runtime. 

I wonder if this is an actual runtime issue in practice. With Gradle, I am pretty sure the version alignment will choose the most recent asm. With Maven, the version it picks is the "nearest" one (see [Dependency mediation](https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#transitive-dependencies)) so that could be problematic.

**Comment by marcingrzejszczak** [comment]
Can't we add excludes in Spring Cloud Contract and just verify whether things still work fine?

**Comment by bono007** [comment]
@marcingrzejszczak yes we can. My point was just that until the same is done in Spring Boot Starter Test the old asm will still be reported in the dependency convergence. I will go ahead and make that change here in SCC and then will follow up with an MR in SBT to do the same.

**Comment by bono007** [comment]
Also, on the Spring Boot side -> https://github.com/spring-projects/spring-boot/pull/24264
