### ISSUE TITLE
Bump Docker image to latest LTS

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-cloud/spring-cloud-contract#1579]

**Comment by plamentotev** [comment]
@marcingrzejszczak 4d71108e4f76fe6829ef64735ed745c1201da44a bumps Ubuntu to `21.04`. I wonder if this is intentional as `21.04` is not yet released version and it is not going to be LTS when released.

Also I wonder if there is specific reason to use SDKMAN! for installing the JDK instead of using the Adopt JDK Docker image? Especially given that the docker file does not use multistage build and SDKMAN! is left on the image, which makes the resulting Docker image larger in size.
