### ISSUE TITLE
3.0.0.RC1 generated test compares kafka header to String, though it is byte array

### ISSUE THREAD

**Issue by Stmated** [spring-cloud/spring-cloud-contract#1587]
I am using version 3.0.0-RC1 of Spring Cloud, and I'm trying to create a test for Kafka. In it comes a header test.
So the contract says something like:

```
outputMessage:
  sentTo: "booked"
  headers:
    BOOK-HEADER: "foo"
```

But when you create a Kafka `ProducerRecord` it only takes headers as byte-array values, not string. So when I send a message from somewhere in the code like:
```
var producerRecord = new ProducerRecord<String, BookingResult>("booked", ...);
producerRecord.headers().add("BOOK-HEADER", "foo".getBytes(StandardCharsets.UTF_8));
this.kafkaTemplate.send(producerRecord);
```

And the generated test is:
```
ContractVerifierMessage response = contractVerifierMessaging.receive("booked", ...);
assertThat(response.getHeader("BOOK-HEADER").toString()).isEqualTo("foo");
```

It will fail with something along the line of "Expected 'foo' given '[B@58372a00'".

Something I could do is create a custom `ContractVerifierMessaging` bean that does this header conversion for me, but feels like it should be able to be solved in a better way?

I can understand if this is not so simple, since the contract does state a string, and that is not what is returned.
But I can't really see how this is supposed to be done properly?

**Comment by bono007** [comment]
It is an interesting problem because header values in Kafka are `byte[]` (as you have pointed out) and the content in those `byte[]` is application specific. There is no type information associated with them. The reasoning why that is the case can be seen in [KIP-82](https://cwiki.apache.org/confluence/display/KAFKA/KIP-82+-+Add+Record+Headers#KIP82AddRecordHeaders-ProducerRecord%3CK,H,V%3E,ConsumerRecord%3CK,H,V%3E).

Additionally, the code that builds that [particular clause](https://github.com/spring-cloud/spring-cloud-contract/blob/master/spring-cloud-contract-verifier/src/main/java/org/springframework/cloud/contract/verifier/builder/MessagingHeadersThen.java#L59) always calls `toString()` on the header value (except when number) which will always result as the memory address of the `[B@58372a00'"` (the header value `byte[].toString()`) being compared against the contract value (`"foo"`). 

It does feel like the header value must be converted in the incoming message in order to match the generated test rules. Again, because the headers can be any arbitrary object and are application specific, converting them all to String would not work in all cases. 

@stmated have you poked around the [sample projects](https://github.com/spring-cloud-samples/spring-cloud-contract-samples/) for any other similar cases doing things w/ Kafka header values? 

@marcingrzejszczak I am curious to what your thoughts are on this one?

**Comment by bono007** [comment]
Sounds good @marcingrzejszczak . I will look into that in the next 1-2 days.

**Comment by Stmated** [comment]
The way that I solved it is some week ago is by in my test cases supplying a `@TestConfiguration` with this:

```
        @Bean
        @Primary
        public ContractVerifierMessaging<Message<?>> contractVerifierKafkaMessaging(MessageVerifier<Message<?>> exchange) {
            return new ContractVerifierMessaging<>(exchange) {

                @Override
                protected ContractVerifierMessage convert(Message<?> message) {

                    final var stringMap = new HashMap<String, Object>();
                    for (final var e : message.getHeaders().entrySet()) {
                        if (e.getValue() instanceof byte[]) {

                            final var bytes = (byte[]) e.getValue();
                            final var str = new String(bytes, StandardCharsets.UTF_8);

                            stringMap.put(e.getKey(), str);
                        } else {
                            stringMap.put(e.getKey(), e.getValue());
                        }
                    }

                    final var stringHeaders = new MessageHeaders(stringMap);

                    return new ContractVerifierMessage(message.getPayload(), stringHeaders);
                }
            };
        }
```

Which works, but feels bad for two reasons:
* It assumes that any bytes is a string.
* It assumes that string is UTF-8.

People mostly do use UTF-8 these days; but it does feel like quite the assumption, and a source of possibly hard-to-solve bugs when your contract stub runner fails with not-matching pairs of strings and you'd assume the error is on the side of the Kafka message and not the test case intermediary.

I am not sure it's the better solution, but I think I'd actually prefer a solution that changed how `MessagingHeadersThen.java` did its comparison. That it would recognize that it's a byte array and then do multiple attempts at matching for the first header, maybe by even going through `Charset.availableCharsets()` (but trying UTF-8 and ISO-8859-1 first) and seeing if any of them match, and then using that same discovered charset for the rest of the headers. This would take it as an error if you've used different charsets for different headers, which might even be a good thing.

**Comment by marcingrzejszczak** [comment]
I think that the best solution is to use the middleware based approach (producer: https://github.com/spring-cloud-samples/spring-cloud-contract-samples/tree/master/producer_kafka_middleware and consumer: https://github.com/spring-cloud-samples/spring-cloud-contract-samples/tree/master/consumer_kafka_middleware). I'm starting to consider to deprecate the in-memory approach for the messaging systems, really.

**Comment by bono007** [comment]
> Sounds good @marcingrzejszczak . I will look into that in the next 1-2 days.

@marcingrzejszczak - it looks like I totally dropped the ball on this one. I forgot about it until I saw this reply. I will make sure I follow through w/ the same above comment. 

I will probably implement your suggested simple fix. That way, even if embedded is deprecated, this bug gets closed. 

As for the deprecation.. I ❤️ testcontainers.io but am unable to use them at work due to security concerns around the docker permissions it requires. I don't agree w/ the concerns, but nonetheless we can't use it. I am curious how many other orgs are in this same boat.

**Comment by Stmated** [comment]
>  I am curious how many other orgs are in this same boat.

Not same boat per se, but I'd say it generally feels very inconvenient to have to have an external dependency (Docker) installed, to be able to use functionality.

**Comment by marcingrzejszczak** [comment]
Yeah makes sense... The thing is that in this case we are actually replicating a broker functionality in a test scope :grimacing: Also it doesn't have to be docker really. You can work against a running broker system so you could just start kafka / rabbitmq before. I know that it's extremely inconvenient but I'm just thinking out loud about the best approach from maintainability perspective too.

**Comment by marcingrzejszczak** [comment]
Does anyone have a sample that I can poke around with?

**Comment by bono007** [comment]
> Does anyone have a sample that I can poke around with?

I don't have one handy @marcingrzejszczak . I am going to look at this issue as soon as I free up w/ a Kafka Streams dumpster fire I am battling.
