### ISSUE TITLE
Docker image - root required

### ISSUE THREAD

**Issue by szczad** [spring-cloud/spring-cloud-contract#1639]
**Describe the bug**
The Docker image runs on root by default which is both insecure and prevents the container from running in secured environments (like Gitlab CI).
If the user is specified (i.e. by providing `--user 1000` flag), the container fails.

**Sample**
```
❯ docker container run --user 1000 --rm -ti springcloud/spring-cloud-contract:3.0.2 ./gradlew clean build

ERROR: JAVA_HOME is set to an invalid directory: /root/.sdkman/candidates/java/current/

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.
```

**Comment by thanhj** [comment]
```
abc
```

**Comment by bastiandoetsch** [comment]
@marcingrzejszczak will try to submit a PR today to have it run with a non-privileged user (1000:1000). @szczad specifying an arbitrary user won't work, as the user would need to be created in the docker image first.

**Comment by marcingrzejszczak** [comment]
Great! I was also thinking whether maybe we shouldn't be using Paketo buildpacks to actually properly build the docker image. WDYT ?

**Comment by bastiandoetsch** [comment]
Yeah I could look into that, too. Building the image right now directly, but build packs would be definitely nicer.

On Aug 9, 2021, at 13:51, Marcin Grzejszczak ***@***.******@***.***>> wrote:



Great! I was also thinking whether maybe we shouldn't be using Paketo buildpacks to actually properly build the docker image. WDYT ?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fspring-cloud%2Fspring-cloud-contract%2Fissues%2F1639%23issuecomment-895159308&data=04%7C01%7Cbdoetsch%40vmware.com%7C37f92dcc1b3f43d1d44708d95b2c10c6%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C637641067089854531%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=21do6w3X0vF65br70GsROEXyH5QYLSnM%2BatQrkUo9Ic%3D&reserved=0>, or unsubscribe<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAEZXT2MPCOAA4B2Z2DFH3KLT366NDANCNFSM427GEN3Q&data=04%7C01%7Cbdoetsch%40vmware.com%7C37f92dcc1b3f43d1d44708d95b2c10c6%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C637641067089864486%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=M6B7Hu13j8yV%2FgQNglEaR1xQRUGwhFuAbsvReMJR79U%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cbdoetsch%40vmware.com%7C37f92dcc1b3f43d1d44708d95b2c10c6%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C637641067089864486%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=wUV6AQ%2FpvDeipxiQpWN6dfj8fQ%2Fn5xLytoqNp0zdwCY%3D&reserved=0> or Android<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7Cbdoetsch%40vmware.com%7C37f92dcc1b3f43d1d44708d95b2c10c6%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C637641067089874443%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=51hkZUb9IBCoIaAtcKVYDUo3nIwkFSnnZPnC2FLel0Q%3D&reserved=0>.

**Comment by ciberkleid** [comment]
I did this in the following way:

1. Remove the following from spring-cloud-contract-stub-runner-boot/pom.xml:
                  <dependencies>
                    <dependency>
                      <groupId>org.springframework.boot.experimental</groupId>
                      <artifactId>spring-boot-thin-layout</artifactId>
                      <version>${thin-jar.version}</version>
                    </dependency>
                  </dependencies> 
2. Run: 
`./mvnw clean spring-boot:build-image -pl spring-cloud-contract-stub-runner-boot`

I assume if the kafka and rabbit dependencies are added in their non-thin configurations, that's all that woul be needed?
I also included actuator in my build... It was good to have some endpoints at :8750 to test and also I envision if this is ever run on Kubernetes it might be helpful to have the health endpoints (liveness/readiness). Would be great if all of the stubs registered with the mappings endpoint, but I don't see that happening today.

**Comment by marcingrzejszczak** [comment]
Actually using the buildpacks may be a breaking change so if we can start with fixing the current docker setup then that would be a good start

**Comment by bastiandoetsch** [comment]
I have a version ready on my branch, gotta test it though. It's here: https://github.com/bastiandoetsch/spring-cloud-contract/tree/issue_1639_Docker_image_-_root_required
On Aug 9, 2021, at 20:32, Marcin Grzejszczak ***@***.******@***.***>> wrote:



Actually using the buildpacks may be a breaking change so if we can start with fixing the current docker setup then that would be a good start

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fspring-cloud%2Fspring-cloud-contract%2Fissues%2F1639%23issuecomment-895444958&data=04%7C01%7Cbdoetsch%40vmware.com%7C99cece1e781047daa76f08d95b63fb86%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C637641307244529844%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=qJJ%2BtdTZm79CZt8wU2NXpp8X6BcSKXEvVAh9nNP8FJM%3D&reserved=0>, or unsubscribe<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAEZXT2LPFOMYOTFA3JYD32TT4ANKDANCNFSM427GEN3Q&data=04%7C01%7Cbdoetsch%40vmware.com%7C99cece1e781047daa76f08d95b63fb86%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C637641307244539798%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=bdorhQfo68xtXuNfaI%2B%2FzHWcTPUOR7CzXwj6U1wAJEI%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cbdoetsch%40vmware.com%7C99cece1e781047daa76f08d95b63fb86%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C637641307244539798%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=bltNFVOAe5Y3L4rO6sZufoY87VADiS4Y%2FTiqzvIU%2F6g%3D&reserved=0> or Android<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7Cbdoetsch%40vmware.com%7C99cece1e781047daa76f08d95b63fb86%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C637641307244549754%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=z7d0LxNAweuOIOb%2BLDicGHcTTlkrxT9EPnfxPUpDfyU%3D&reserved=0>.
