### ISSUE TITLE
xpath byCommand not generating correctly 

### ISSUE THREAD

**Issue by markgargan** [spring-cloud/spring-cloud-contract#1651]
From the spring cloud contract documentation here 
https://cloud.spring.io/spring-cloud-contract/reference/html/project-features.html

there's a particular xpath matcher in the bodyMatchers of the xml example
xPath('/test/duck/text()', byCommand('equals($it)'))

However in the generated test class in the docs there's no mention of the equals method?
When I try this in a test it just produces the following
equals("")
in the test without passing the code to extract the text of the duck node to the method? 
Is this functionality that's coming down the line? 

Thanks,
Mark.

**Comment by marcingrzejszczak** [comment]
` xPath('/test/duck/text()', byCommand('equals($it)'))` - `byCommand` is a Spring Cloud Contract utility that allows you to execute custom code for the producer side assertion. `equals()` is a method that comes from Java on each object - that's why our tests pass. What happens is that we take the result of the `/test/duck/text()` evaluation and we pass it to `equals()` method as a parameter.

BTW the new docs are here https://docs.spring.io/spring-cloud-contract/docs/current/reference/html/
