### ISSUE TITLE
Removing 2 messaging contract types - leaving just the "supplier" version

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-cloud/spring-cloud-contract#1837]
done via https://github.com/spring-cloud/spring-cloud-contract/pull/1831/commits/1999066c5af7af2692b2897fc9ca70215534e3cc

**Comment by kwonglau** [comment]
What is the migration path for "Output Triggered by a Message" ?

Currently, the java microservice framework is using spring cloud contract 3.x and it is depending on that for contract testing

https://github.com/eventuate-tram/eventuate-tram-core/blob/master/eventuate-tram-spring-testing-support-cloud-contract/src/main/java/io/eventuate/tram/spring/cloudcontractsupport/EventuateTramRoutesConfigurer.java#L53

**Comment by marcingrzejszczak** [comment]
Check this page https://github.com/spring-cloud/spring-cloud-contract/wiki/Spring-Cloud-Contract-4.0-Migration-Guide#leave-only-code-input-triggers-and-output-message-type

**Comment by keydon** [comment]
hmm very sad you are letting the inputMessage feature go. Most of our rabbit-endpoints are following the request-response pattern. So for me it is exactly the same use-case as an http-endpoint. but now if I understand it right its no longer testable with a single contract and without code :( I guess I would need to write at least two contracts, wire-in a stub-runner for each-client. And I would need to trigger a producer-stub-within a consumer-trigger. A lot of moving parts for a simple RPC-Call.

But since I am the only one who is sad to see this feature go I guess its not coming back, is it?
Now I am thinking about adding a HTTP-Wrapper around my Rabbit-RPC-Endpoints. So I can still have a single contract, and the custom HTTP-Wrapper can be generic and reusable for every other test. Our is there an easier way to test a RPC-Endpoint? Maybe you could add a RCP Example to the other examples repo.

and btw. all the docs about the contracts that I can accross are still on the old version and advertising this cool inputMessage feature.

**Comment by keydon** [comment]
about the outdated docs, I mean the published ones here:
https://cloud.spring.io/spring-cloud-contract/reference/html/project-features.html#features-messaging-scenario2 seems to be based on the old "3.0.0-SNAPSHOT" sources

**Comment by marcingrzejszczak** [comment]
These are old docs that have been migrated away from years ago. This is the latest version of the docs https://docs.spring.io/spring-cloud-contract/docs/current/reference/html/

**Comment by keydon** [comment]
seems nobody told google about it ;O

**Comment by ranjitsinghpe** [comment]
Hi @keydon did you have luck implementing the two separate contracts, I am struggling to understand which part stays in producer. I use spring cloud stream binders to work with my queues/topics. 
I imagined this to work like this 
Producer creates the stub with all the contracts ( messageFrom, sentTo). 
Consumer uses stub runner to trigger the contract label to verify 

Are you able to elaborate how you achieved this ?
` I guess I would need to write at least two contracts, wire-in a stub-runner for each-client. And I would need to trigger a producer-stub-within a consumer-trigger`

**Comment by alexpophal** [comment]
So, we can also use messaging as a form of asynchronous communication not only as event publishing. As obvious as this statement is I am trying to call the attention to the fact that for asynchronous communication we would have a request and a response, just like in the case of http endpoints. So, if we are saying that the contract test for messages can be split into 2 separate tests, so could the http contract, right? I may be the only one using the contract test to not only test the schema of the message but also the protocol in the sense that I have an id field in the outbound message that should appear in the inbound message. Without the removed functionality I do not see I way I can test both matches. I am left to only test the schema of my messages not the protocol.

**Comment by marcingrzejszczak** [comment]
From the technical perspective there are so many messaging options out there that it's close to impossible to ensure that all of those are mocked. With HTTP it's enough to use a single mocking solution (like WireMock). 

Still you can test your scenario without big hussle. The very idea of integration tests is that you test in isolation the edges (or ports / adapters whatever you call those). That's why you would have an integration test for the listener and for the sender. In the middle you'll have some sort of a service that you can also test in isolation.

If you want to test the whole process "end to end" you can use the stub runner to send a message to your listener and then you can assert manually that whatever you want there in the output message is there.

Also I do not agree with the statement that checking that the outbound message has an id field that is the same as in the inbound one is checking of the protocol. It's checking of a business feature (unless I misunderstood sth).

**Comment by alexpophal** [comment]
Thanks for the quick response, Marcin. Indeed, messaging has no standard on how it can be implemented, as opposed to http. In fact, I had to write an extension myself as my company uses SNS/SQS and also a wrapper around it. I was surprised to see how the current design of the spring contract allowed me to do that quite easily (Thanks)

Regarding testing this scenario using end to end tests. I may be stretching spring contract on what it was meant to be used for, but I was wondering if we could slice end to end tests using the contracts between consumers and producers. If so, I may be able to reduce the number of end to end tests in my system as these tests tend to be brittle and much slower than local tests replacing some(although not all) by contract tests. For that, instead of mocking things and tempering with requests and response messages I just run my service with its complete context when I trigger the contract tests. This approach works great for http, but I have this caveat with messages as the async request/response seems to not be supported by spring contract.

Last, when I am referring to the protocol, I meant the things consumers and producers agree upon which has nothing to do with business feature. In this instance, the agreement would be the consumer will send an id that it expects the producer to send back so it can relate a request to a response. Business does not care whether we use asynch or synch communication neither whether we need an id in the messages, hence, it cannot be a business feature. I am referring to it as part of the communication protocol, but I am happy to give this another name.

**Comment by marcingrzejszczak** [comment]
> Thanks for the quick response, Marcin. Indeed, messaging has no standard on how it can be implemented, as opposed to http. In fact, I had to write an extension myself as my company uses SNS/SQS and also a wrapper around it. I was surprised to see how the current design of the spring contract allowed me to do that quite easily (Thanks)

I'm glad that you like it :)

> Regarding testing this scenario using end to end tests. I may be stretching spring contract on what it was meant to be used for, but I was wondering if we could slice end to end tests using the contracts between consumers and producers. If so, I may be able to reduce the number of end to end tests in my system as these tests tend to be brittle and much slower than local tests replacing some(although not all) by contract tests. For that, instead of mocking things and tempering with requests and response messages I just run my service with its complete context when I trigger the contract tests. This approach works great for http, but I have this caveat with messages as the async request/response seems to not be supported by spring contract.

One of the first users of Spring Cloud Contract was using it in that way and IMO this is abusing of contract approach. Of course what I think doesn't matter if it serves a purpose ;) The thing is that from support perspective it's very difficult and time consuming to leave the support for the request / reply feature - that was also one of the reasons why we've removed the support.

> Last, when I am referring to the protocol, I meant the things consumers and producers agree upon which has nothing to do with business feature. In this instance, the agreement would be the consumer will send an id that it expects the producer to send back so it can relate a request to a response. Business does not care whether we use asynch or synch communication neither whether we need an id in the messages, hence, it cannot be a business feature. I am referring to it as part of the communication protocol, but I am happy to give this another name.

I still don't see that being part of the contract. Contract is about testing semantics. You may or may not have the same id there from the semantic point of view. It's your technical / business requirement for that to be the same and you should test it with a proper e2e (if you need to test it).
