### ISSUE TITLE
When Adding Gradle checkstyle plugin - Contract Tests are not executed

### ISSUE THREAD

**Issue by huffleman51** [spring-cloud/spring-cloud-contract#223]
I added the checkstyle plugin to my build.gradle file and the contract tests get generated but the tests are not executed during the test phase. When I check the test results zero tests ran. I tried adding checkstyle to the producer_with_external_contracts sample project and I am seeing the same behavior. 

spring-cloud-contract-samples/producer_with_external_contracts/build/reports/tests/test/index.html

![with checkstyle added](https://cloud.githubusercontent.com/assets/7205521/22829921/b491f81c-ef72-11e6-96ae-00d3198a63f7.png)

![without checkstyle](https://cloud.githubusercontent.com/assets/7205521/22829993/f8448958-ef72-11e6-814c-78db0fc6efe4.png)

[Test Reports.zip](https://github.com/spring-cloud/spring-cloud-contract/files/766933/Test.Reports.zip)

**Comment by marcingrzejszczak** [comment]
I've found a solution to this finally. Unfortunately Checkstyle is altering the order of executing tasks. Just add this to every build you have

```
if (tasks.findByName("checkstyleTest")) {
	checkstyleTest.mustRunAfter 'generateContractTests'
}
```

and that way you'll enforce checkstyle at the end after the contract tests have been generated. I prefer not to hardcode these things in the plugin as such since every plugin can behave in a different way. Is this answer acceptable for you?

**Comment by marcingrzejszczak** [comment]
You can check out the latest snapshots (once they're built) cause I fixed the "dependsOn" property on the generate contract tests task

**Comment by huffleman51** [comment]
I tested this with the latest build and the contract tests are being generated and executed during a build with checkstyle enabled.  Thanks!

**Comment by marcingrzejszczak** [comment]
I'm really happy to hear that :)
