### ISSUE TITLE
Fix the test resources

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-cloud/spring-cloud-contract#286]
In Gradle plugin we're adding test resources if someone's using the intellij plugin. I guess we should be always be adding the generated tests to test resources regardless of the presence of the plugin.

**Comment by lnhrdt** [comment]
@marcingrzejszczak would you consider changing this so that we add the test resources regardless of detecting IntelliJ? The current implementation looks for the presence of a `.idea/` folder. I have a Gradle multi-project setup and my producer app is in a subdirectory, causing the generated tests not to be added to test resources, unless I manually add a `.idea/` folder to the subdirectory. This makes setting up the project on multiple machines a little clumsy.

**Comment by marcingrzejszczak** [comment]
Hi! Afair we always add it. The idea thing is only to force intellij to see that.

**Comment by lnhrdt** [comment]
Oh I get it. Maybe there's a better way to determine if IntelliJ is present since checking for `.idea/` in the project directory doesn't always cover it. I'll see if I can come up with something.

**Comment by marcingrzejszczak** [comment]
Yeah definitely you're right. It needs to be fixed. I'll reopen the issue

**Comment by marcingrzejszczak** [comment]
I think that it's enough to check the root project if it has the `.idea` folder. WDYT?

**Comment by marcingrzejszczak** [comment]
I've fixed it in latest `1.1.2.BS` - you can check out if it's working fine for you
