### ISSUE TITLE
Add support for Rest Assured tests with Spring RESTdocs

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-contract#334]
Spring RESTdocs has support for full stack tests with snippet generation using Rest Assured, and Rest Assured is already a dependency in spring-cloud-contract for other reasons, so it makes sense to make the RESTdocs bit work the same as it does with MockMvc.

**Comment by eddumelendez** [comment]
is this issue still planned for version `1.2.0`? I have sent a PR  https://github.com/spring-projects/spring-boot/pull/9643 in order to support RestDocs RestAssured auto-configuration which is planned for spring-boot `2.0.0`.

I would like to work on this, so should I wait? or spring-cloud-contract can provide restassured configuration for `1.2.0` and when moving to `2.0.0` should be aligned with the auto-configuration provided by spring-boot?

**Comment by dsyer** [comment]
I already have some code that works here if it helps: https://github.com/dsyer/spring-cloud-netflix/blob/feature/eureka-stubs/spring-cloud-netflix-eureka-server/src/test/java/org/springframework/cloud/netflix/eureka/server/doc/AbstractDocumentationTests.java. It would be a lot neater if it was backed by Spring Boot natively, and I'm not sure it makes sense to add features in spring-cloud-contract until Boot catches up, given that it is relatively easy to write custom code to integrate RestAssured.

Maybe we can persuade the Boot team to backport to 1.5.x (I don't see any reason why it wouldn't work)? Then we could do it in 1.x.

**Comment by eddumelendez** [comment]
Indeed it would be cool the approach to backport. I just add one more commit https://github.com/spring-projects/spring-boot/pull/9643/commits/826c0f84cd21f1b7ebcd43daea99c34eac1bb5b9 to mi initial PR in order to provide the customizer needed by spring-cloud-contract and make the integration easier.

May @wilkinsona can add few comments about the idea to backport restassured integration to spring-boot `1.5.x`.

**Comment by wilkinsona** [comment]
I am not keen on backporting to 1.5.x as that would be REST Docs 1.1 and REST Assured 2

**Comment by marcingrzejszczak** [comment]
@dsyer since the code will not be backported, will you apply your patch also here or do you want me to do it? We can also assume that the support will be there out of the box with version `2.0.0`, right?

**Comment by dsyer** [comment]
That wasn't my reading of the above (or maybe I misunderstood you). Spring Boot 1.5.x will not have the customizer hooks we need, but 2.0.x will. We still need to add some code to Spring Cloud Contract I think (to match the features in `MockMvc`), so it will be easier to do in 2.0.x, and I assume we will leave 1.x as an implementation exercise for users (possibly copying the code I used above). If @eddumelendez wants to do the work, that's awesome.

**Comment by marcingrzejszczak** [comment]
Ok then so I'll mark this as to be done for `2.0.x`. If the users have something prepared for `1.5.x` boot then we will work on the PR.

**Comment by marcingrzejszczak** [comment]
Done via https://github.com/spring-cloud/spring-cloud-contract/pull/431
