### ISSUE TITLE
Consider merging Stub Runner and WireMock starters

### ISSUE THREAD

**Issue by jkubrynski** [spring-cloud/spring-cloud-contract#348]
As the use-case for those starters is similar we could merge them into one starter. It will simplify user experience when starting the journey with contracts.

**Comment by marcingrzejszczak** [comment]
Since there is no separate starter for `WireMock`, we suggest using `spring-cloud-starter-contract-stub-runner` starter, that includes `spring-cloud-contract-wiremock`. We will update the documentation for `2.0.0` and update initlizr for `2.0.0` so it DOESN'T include a separate `spring-cloud-wiremock` dependency

**Comment by marcingrzejszczak** [comment]
The initlizr PR https://github.com/spring-io/initializr/pull/629
