### ISSUE TITLE
Inconsistent regex() usage and invalid client stubs after passed server verification

### ISSUE THREAD

**Issue by mariuszs** [spring-cloud/spring-cloud-contract#389]
Contract without explicit `regex()` method before `onlyAlphaUnicode()` or `email()` compiles stubs and pass verification, but as the result stubs are invalid on client side.

```
import org.springframework.cloud.contract.spec.Contract

Contract.make {
  request {
   	method 'POST'
    url "/candidates"	
    body(
      uuid: $(value(consumer(anyUuid()), producer('554833c9-2f7c-498f-a137-78dc2a265691'))),
      name: $(value(consumer(onlyAlphaUnicode()), producer('John'))),				
    )
    headers {
      contentType(applicationJson())
    }    
  }
  response {
    status 201
}

```

results in stub definition:

```
 "bodyPatterns" : [ {
      "matchesJsonPath" : "$[?(@.['uuid'] =~ /[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}/)]"
    }, {
      "matchesJsonPath" : "$[?(@.['name'] == '[\\p{L}]*')]"   // <-INVALID HERE
    }, {

```

After adding `regex()`:

`      name: $(value(consumer(regex(onlyAlphaUnicode())), producer('John'))),				`

all works fine.

Mappings looks like:

    "bodyPatterns" : [ {
      "matchesJsonPath" : "$[?(@.['uuid'] =~ /[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}/)]"
    }, {
      "matchesJsonPath" : "$[?(@.['name'] =~ /[\\p{L}]*/)]" // VALID NOW

Some types doesn't require `regex()` method at all, for example `anyUuid()` and `anyBoolean()`.

    uuid: $(value(consumer(anyUuid()), producer('554833c9-2f7c-498f-a137-78dc2a265691'))),
    required: $(value(consumer(optional(anyBoolean())), producer(true))),

```

**Comment by marcingrzejszczak** [comment]
If you read the docs you'll see this section

https://cloud.spring.io/spring-cloud-contract/spring-cloud-contract.html#_regular_expressions

Those methods expressed in that section are returning `String` so you need to wrap it in `regex(...)`. 

So that it's easier for the developers we've created a shortened version of these patterns:

https://github.com/spring-cloud/spring-cloud-contract/blob/master/spring-cloud-contract-spec/src/main/groovy/org/springframework/cloud/contract/spec/internal/PatternValueDslProperty.groovy#L38-L100

The latter are not described in the docs from what I see which is definitely not good. Do you suggest some concrete solution to this problem? Would adding some suffix to the first ones (e.g. `Regex`) `onlyAlphaUnicodeRegex` be more clear?

**Comment by marcingrzejszczak** [comment]
After a short discussion, we came to the conclusion that it's confusing for `RegexPatterns` to return `String`. When defining the `consumer/producer` pair, you can easily create by mistake 2 string values if you forget the `regex(...)` and then you will only notice the issues on the consumer side due to invalid regular expression.

So the solution would be to change the current return types to `Pattern`. The `regex(String)` method will remain but also we need to add `regex(Pattern)` to maintain the compatibility of current DSLs. `regex(Pattern)` will return just the `Pattern`.

After such a change failing fast will be much easier.

**Comment by marcingrzejszczak** [comment]
Done via https://github.com/spring-cloud/spring-cloud-contract/commit/27a481ce2545585b5893aa71d2d7e322387c5027
