### ISSUE TITLE
Issues with special characters

### ISSUE THREAD

**Issue by szisti** [spring-cloud/spring-cloud-contract#435]
Tested on the following versions:

- 1.1.1
- 1.1.4
- 1.2.0

When expecting a string as response (not a JSON) the ">" character gets converted twice into "&amp;gt;" and fails the test
Also having problems with multiple curly bracket pairs

Created a sample project showing these problems:
https://github.com/szisti/contract-demo

**Comment by marcingrzejszczak** [comment]
You have a bug in your tests

```
Contract contractDsl = Contract.make {
				description "Get breadcrumb"
				request {
					url "api/breadcrumb"
					method GET()
				}
				response {
					status 200
					headers {
						header(contentType(), applicationJson())
					}
					body("Home > Settings > Preferences")
				}
			}
```

You define that this is a JSON but the body is a text. Just change 

`header(contentType(), applicationJson())` -> `header(contentType(), textPlain())`

as for the curly issue that's really interesting cause in order to do referencing of request in the response we need to use the mustache template which looks like this `{{{ }}}`. So if you use it in the response then it will try to apply the template. Do you really need to test this text in the body or are you just playing around with the framework? Cause if it's the latter then I'll close the issue for now and if anybody actually has this issue then I'll try to fix it. WDYT?

**Comment by szisti** [comment]
Can be closed
