### ISSUE TITLE
Possibility to verify call to one of the collabolators

### ISSUE THREAD

**Issue by pilloPl** [spring-cloud/spring-cloud-contract#457]
Hi,
Many spring-cloud-contract-based projects I have chance to work at are in need to verify that some call was made to a different service.

E.g. I am issuing a command to an external system and I don't care (in the test) about how the response looks like. Contrary to when I am issuing a query and I want a specific response.

I was thinking for a while how it could work and the best and simplest idea would be to rely on wiremock API. So that it could be possible to run verify methods from wiremock that is backing a specific collaborator. 

I already have worked it around to have both pure wiremock and stubrunner in a single test around but it is very hard and not readable and causes confusion and possible bugs.

**Comment by marcingrzejszczak** [comment]
Hi @pilloPl 

you can already do all of that with 1 line of code.

Let's imagine that we have the following stub:

```json
{
  "request" : {
    "url" : "/name",
    "method" : "GET"
  },
  "response" : {
    "status" : 200,
    "body" : "loanIssuance"
  }
}
```
I have config like this:

```yaml
stubrunner:
  repositoryRoot: somePath
  ids:
    - org.springframework.cloud.contract.verifier.stubs:loanIssuance
    - org.springframework.cloud.contract.verifier.stubs:fraudDetectionServer
    - org.springframework.cloud.contract.verifier.stubs:bootService
```

So now if you have a test looking like this:

```groovy
@ContextConfiguration(classes = ..., loader = SpringBootContextLoader)
@SpringBootTest(...)
@AutoConfigureStubRunner(...)
class StubRunnerConfigurationSpec extends Specification {

	def 'should verify that the call was made via WireMock API'() {
		given:
			URL url = stubFinder.findStubUrl('loanIssuance')
		when:
			"${url.toString()}/name".toURL().text == 'loanIssuance'
		then:
			new WireMock(url.host, url.port)
					.verifyThat(1, getRequestedFor(urlEqualTo("/name")))
	}

}

```

The test will pass. If I change the `urlEqualTo("/names")` - the test will fail due to:

`com.github.tomakehurst.wiremock.client.VerificationException: No requests exactly matched. Most similar request was:   <Click to see difference>`

Now, why you can do it like this? `new WireMock(host, port)` creates the client side of WireMock interaction. When WireMock server starts, you can access it via `new WireMock(host, port)` and then you can verify whatever you want via the WireMock's API.

If you used Moco, or some other server, I'm pretty sure it works in the same way. All of these servers have their own, unique way of verifying whether a piece of API was called. It would be difficult to apply a single API for this. I'm pretty sure that writing one line of code by the user that wants to perform verifications is much easier.
