### ISSUE TITLE
PathNotFoundException when request body wraps into """ """

### ISSUE THREAD

**Issue by tblasig** [spring-cloud/spring-cloud-contract#458]
With a body wrapped into ''' or """ : 

`
body("""
{
  name: "My name"
}
""")
`
After doing  ${fromRequest().body('$.name')} in the response body I got the following exception : 
[PathNotFoundException.log](https://github.com/spring-cloud/spring-cloud-contract/files/1474957/PathNotFoundException.log)

> > inline@75af6e18:101:62: com.jayway.jsonpath.PathNotFoundException: Expected to find an object with property ['name'] in path $ but found 'java.lang.String'. This is not a json object according to the JsonProvider: 'com.jayway.jsonpath.spi.json.JsonSmartJsonProvider'.
      inline@75af6e18:101:62

PS: When the body is unwrapped it works.

**Comment by marcingrzejszczak** [comment]
There was a bug and your json was invalid (it should be `body(""" { "name": "My name" } """)` ). Thanks for filing the issue :)

**Comment by surya5678** [comment]
is the above issue is fixed?

**Comment by marcingrzejszczak** [comment]
As you can see by looking at the information that the issue is `closed`, you have the version when it was closed `1.1.5` and a commit that closed it https://github.com/spring-cloud/spring-cloud-contract/commit/3bbdda83a9cdab67479c8d91a44da07b5212907f then we can assume that it is fixed and closed :)
