### ISSUE TITLE
Ensure that Maven plugin can use password / username to download contracts

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-cloud/spring-cloud-contract#462]

**Comment by jorgeviana** [comment]
I have a problem and I don't know if it is related with this one. Perhaps you can tell.
When I use the annotation AutoConfigureStubRunner in online mode, I just pass the properties stubrunner.username and stubrunner.password and everything is ok.
But when I use StubRunnerRule I cannot make it work, I tried with system properties and also with StubRunnerOptionsBuilder().withUsername("xxx").withPassword("xxx").build()

**Comment by marcingrzejszczak** [comment]
Which version are you using? Also, can you show how exactly you use it?

**Comment by jorgeviana** [comment]
Perhaps this could be created a separate issue. Either case, do you think that a workaround will be possible?

**Comment by jorgeviana** [comment]
I investigated a bit more and I was able to reproduce this at home. I set up a Nexus repository in my laptop using some Docker image and configured it to **not** have anonymous access to repos.
The problem is as I described before, with annotation AutoConfigureStubRunner works, with ClassRule doesn't work.
I then enabled anonymous access to repos, and both annotation AutoConfigureStubRunner and ClassRule worked.
I would like to investigate deeper in Spring source code but my knowledge of the Spring framework is more on the usage level, I don't have skills to do this alone or without guidance.

**Comment by marcingrzejszczak** [comment]
So when you passed the creds via system properties it didn't work right? Can you paste the dockerfile you've created for the test?

**Comment by jorgeviana** [comment]
Right, when using ClassRule the credentials via system properties does not work. Also doesn't work with StubRunnerOptionsBuilder when trying to set credentials.

I used a Docker image available in https://github.com/sonatype/docker-nexus but I needed to do some administration on it manually after it started (like disabling anonymous user, setting a user/pass for read access). I also deployed there some stubs jar using spring-cloud-contract-maven-plugin.
So this is not a ready made image built to simulate the problem.

**Comment by marcingrzejszczak** [comment]
Can you ping me on gitter about this - https://gitter.im/marcingrzejszczak ?

**Comment by jorgeviana** [comment]
Seems gitter is blocked at my work...

**Comment by marcingrzejszczak** [comment]
Can you send me an email then? `mgrzejszczak (at) pivotal (dot) io` ?

**Comment by marcingrzejszczak** [comment]
I've moved the StubRunnerRule issue here - https://github.com/spring-cloud/spring-cloud-contract/issues/466 . I've managed to replicate the problem locally
