### ISSUE TITLE
Different versions of same artifact are not exposed through stub runner.

### ISSUE THREAD

**Issue by mhmohapatra** [spring-cloud/spring-cloud-contract#474]
stubrunner:
  ids:
  - "yyy:sample-service:1.0.0:stubs:9898"
  - "yyy:sample-service:2.0.0:stubs:9899"

In this instance version 1.0.0 is exposed at port 9899 which is assigned to version 2.0.0.

//cc @bijukunjummen

**Comment by marcingrzejszczak** [comment]
Most likely I have a set somewhere and a lookup via group id and artifact id. What's the usecase of having 2 stubs at the same time?

Of course the workaround would be to run 2 separate tests, right?

**Comment by bijukunjummen** [comment]
Hey @marcingrzejszczak, 
@mhmohapatra and I were working on a sample when we saw this issue. 

We are working on a team which manages a set of microservices, so we have created this centralized stub server portal(using `@EnableStubServerRunner`) with the stubs hosted as wiremock servers. We just wanted to see what the behavior will be if there were two different versions of a microservice hosted on the stub server and saw this issue. 

So this issue is not in a test, but when hosting the stub in a stub server.
