### ISSUE TITLE
Allow generation of stubs at runtime

### ISSUE THREAD

**Issue by jkubrynski** [spring-cloud/spring-cloud-contract#881]
Current situation: to use contracts you have to build them and then publish to maven or git repository. It's pretty hard if you don't have strong Maven/Gradle knowledge. For example, if you want to publish just stubs without application jars it needs some hacking. Tagging production versions of the artifacts is not easy also. As well as downloading stubs from Nexus/Artifactory if you're working with frontend technologies.

Generally, it's possible to introduce simplified and easy to document workflow.
1. Assume we keep contracts in the producer repository (like private GitHub or Stash) - most popular model so far in most companies AFAIK.
2. Developers have at least read-only access to repositories they are collaborating with.
3. For frontend technologies, you can launch docker container just by providing the repository URL and optionally path to contracts (by default `src/test/resources/contracts`). We even don't need to know the groupId, artifactId and version. You can also specify tag or branch (`prod` or `dev`).
4. For backend Java services you can also use git url as in the 3 point and you don't have to deal with stubs versioning (just use the `production` tag.

**Comment by marcingrzejszczak** [comment]
Let's prototype the API!

```java
@AutoConfigureStubRunner(properties = {
// already there				
"stubrunner.git.branch=production", 
// new
"stubrunner.path-to-contract=src/test/resources/contracts" },
repositoryRoot = "git://https://my-producer.com",
// new
generateAtRuntime = true)
```

The new property `stubrunner.path-to-contract` would override the place from which we pick contracts (instead of the default `/META-INF/group-id/artifact-id/stubs` and `/META-INF/group-id/artifact-id/contracts`). That way `ids` are not necessary in this case.

`generateAtRuntime` means that the `stubs` folder will be ignored and depending on what you have on the classpath (defaults to WireMock) would generate stubs at runtime and start WireMock servers at runtime too.

WDYT?

**Comment by TYsewyn** [comment]
That looks like a great start to begin with, and possibly extendable for other use cases too! (dare I mention the pact broker? 😅)
But what will happen when you're consuming from multiple producers, each with their own git repo/branches?
Maybe we can throw in an `@AutoConfigureStubRunners` for this use case?

**Comment by marcingrzejszczak** [comment]
> That looks like a great start to begin with, and possibly extendable for other use cases too! (dare I mention the pact broker? sweat_smile)

for Pact broker it works already like this. On the consumer side, we generate stubs at runtime.

>  But what will happen when you're consuming from multiple producers, each with their own git repo/branches?

:man_shrugging: Different test classes I guess?

>  Maybe we can throw in an `@AutoConfigureStubRunners` for this use case?


```java
@AutoConfigureStubRunners({
@AutoConfigureStubRunner(properties = {
// already there				
"stubrunner.git.branch=production", 
// new
"stubrunner.path-to-contract=src/test/resources/contracts" },
repositoryRoot = "git://https://my-producer1.com",
// new
generateAtRuntime = true),
@AutoConfigureStubRunner(properties = {
// already there				
"stubrunner.git.branch=production", 
// new
"stubrunner.path-to-contract=src/test/resources/contracts" },
repositoryRoot = "git://https://my-producer2.com",
// new
generateAtRuntime = true),
@AutoConfigureStubRunner(properties = {
// already there				
"stubrunner.git.branch=dev", 
// new
"stubrunner.path-to-contract=src/test/resources/contracts" },
repositoryRoot = "git://https://my-producer3.com",
// new
generateAtRuntime = true)
})
```

:scream: :scream: :scream: :scream: :scream: 

## Why do we do this?

Let's maybe take a step back. I understand that this feature is considered to be implemented because we want to hasten the feedback loop. It's not the standard way of working with the tool that we suggest people use.

With the `generateAtRuntime` (draft name of the prop) we could remove one step of prototyping the API. We could point to a folder, git repo, whatever where only contracts lay and regardless of the fact, whether the stub is there or not, we will create one. This can help in situations where the contract is defined but stubs are not and you have to wait endlessly until someone finishes their work on the producer side.

**Comment by wkorando** [comment]
What's the current status of this feature? Based on our conversation at Spring I/O this matches pretty closely to what I was thinking of (though is implemented in a better way than I was suggesting 😅).

I feel like in some ways the "consumer driven" workflow is incomplete until a feature like this is implemented. While a consumer could create a contract, their progress is somewhat blocked until the producer has time to stub out/implement the feature.

**Comment by marcingrzejszczak** [comment]
A prerequisite to this would be https://github.com/spring-cloud/spring-cloud-contract/issues/1150 . That way you don't have to even produce an artifact to run stubs. Just point the repo root to `stubs://file://...` and that way you will run the stubs. Next, we will allow to point to the folder with contract definitions and via a switch convert contract definitions to running stubs at runtime.
