### ISSUE TITLE
Support for JUnit 5.4 - test method ordering

### ISSUE THREAD

**Issue by binkley** [spring-cloud/spring-cloud-contract#887]
re: https://github.com/junit-team/junit5/issues/48#issuecomment-463456291 (and following comment)

Using JUnit5 with Spring Cloud Contract (SCC), I noticed this behavior in 2.1.0:
- Naming a contract (YAML) with a numeric prefix triggers code generation failure, with the message "Not implemented yet in JUnit5 - https://github.com/junit-team/junit5/issues/48"

I tracked it down to https://github.com/spring-cloud/spring-cloud-contract/blob/8ce80e6e7fc0267a9cba1679bdf20f42ce875741/spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/config/framework/JUnit5Definition.groovy#L63.

Initially I posted to the issue link in the message, but find it's really a SCC issue, not a JUnit one.

JUnit 5.4 provides an experimental annotation, `@TestMethodOrder`, with 3 interesting policies:
- Run tests in alphanumeric order based on generated method name
- Run tests in random order
- Run tests in user-specified order using the `@Order` annotation on each test method

Is there any mechanism for YAML format whereby I can ask for annotations on the SCC-generated methods, or possibly on the generated test class?

`@TestMethodOrder` is marked `@Inherited`, so I'm trying out placing it on my test base class, but am encountering issues (Spring framework is behaving oddly, having problems with classpath and loading the context.)

My sample project is http://github.com/binkley/basilisk

**Comment by OlgaMaciaszek** [comment]
Yes, should be added following its introduction to JUnit5.

**Comment by wasyl77** [comment]
Hi, is there any information when / which release this could be added to SCC ?

**Comment by OlgaMaciaszek** [comment]
We will probably wait for it to leave the `Experimental` status, which is when the feature is recommended to be used in prod by the developing team.

**Comment by anatoliy-balakirev** [comment]
Hi @OlgaMaciaszek. Could it be an option to introduce some `JUNIT5_EXPERIMENTAL` type to the `org.springframework.cloud.contract.verifier.config.TestFramework`, which would include experimental functionality and otherwise will be exactly the same as `JUNIT5`?
We have to start using scenarios with SCC, but we've already migrated everything to Junit 5... Really don't like an option to switch back to Junit 4 in contract tests.

**Comment by OlgaMaciaszek** [comment]
Hi @anatoliy-balakirev it's true that this feature has stayed in experimental status for quite a long time now.

@sbrannen maybe you could help: are there any plans of moving out https://junit.org/junit5/docs/current/api/org/junit/jupiter/api/TestMethodOrder.html from experimental to standard feature? (related to https://github.com/junit-team/junit5/issues/48) .

If not, then we will probably have to think about adding it for Hoxton, anyway, cause it probably is blocking a group of users to start using SCC. @marcingrzejszczak wdyt?

**Comment by marcingrzejszczak** [comment]
I'd add it regardless of its experimental state

**Comment by OlgaMaciaszek** [comment]
:+1:  let's add it.

Will work on it on Monday.

**Comment by sbrannen** [comment]
> @sbrannen maybe you could help: are there any plans of moving out [junit.org/junit5/docs/current/api/org/junit/jupiter/api/TestMethodOrder.html](https://junit.org/junit5/docs/current/api/org/junit/jupiter/api/TestMethodOrder.html) from experimental to standard feature?

We typically leave a new feature labeled as experimental for 1-2 releases to see if there are any major issues. So, since we recently released 5.5, it's foreseeable that we will remove the experimental label in 5.6 (to be released later this year hopefully).

Note, however, that we [decided yesterday](https://github.com/junit-team/junit5/issues/1924#issuecomment-521959261) to change the default `@Order` value. Thus, because of that change, the `@Order` annotation might remain _experimental_ until 5.7 (next year).

In any case, aside from the change for the default `@Order` value, I don't foresee any other major changes to the method ordering support.

Long story, short: I think it's OK to start using `@TestMethodOrder` now.

**Comment by OlgaMaciaszek** [comment]
Thanks @sbrannen . That's really helpful. Will add it then.
